-- USER SQL
CREATE USER Renta_House_P2 IDENTIFIED BY "123*"
--DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER PBD_3_2 QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "RESOURCE" TO PBD_3_2 ;
GRANT "CONNECT" TO PBD_3_2 ;
ALTER USER PBD_3_2 DEFAULT ROLE "RESOURCE","CONNECT";