/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/uosEG6fJSuC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import '../app/styles/globals.css'

export function Component() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="fixed top-0 left-0 right-0 z-10 bg-background px-4 py-3 shadow-sm">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-xl font-bold text-foreground" prefetch={false}>
            Portfolio
          </Link>
          <nav className="flex items-center gap-4">
            <Link href="#" className="text-sm font-medium text-foreground hover:underline" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="text-sm font-medium text-foreground hover:underline" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium text-foreground hover:underline" prefetch={false}>
              Projects
            </Link>
            <Link href="#" className="text-sm font-medium text-foreground hover:underline" prefetch={false}>
              Contact
            </Link>
          </nav>
        </div>
      </header>
      <main className="flex-1 pt-20">
        <section className="bg-background py-12 md:py-20">
          <div className="container mx-auto flex flex-col items-center gap-6 px-4 md:flex-row md:gap-12">
            <div className="flex-1">
              <img
                src="/placeholder.svg"
                width={300}
                height={300}
                alt="Profile"
                className="mx-auto h-48 w-48 rounded-full object-cover md:h-64 md:w-64"
                style={{ aspectRatio: "300/300", objectFit: "cover" }}
              />
            </div>
            <div className="flex-1 space-y-4 text-center md:text-left">
              <h1 className="text-3xl font-bold text-foreground">Moises Figueroa</h1>
              <p className="text-muted-foreground">Software Engineer</p>
              <p className="text-muted-foreground">
                I'm a passionate web developer with expertise in creating modern and responsive web applications.
              </p>
              <div className="flex justify-center gap-4 md:justify-start">
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                  prefetch={false}
                >
                  Download CV
                </Link>
                <Link
                  href="#"
                  className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2"
                  prefetch={false}
                >
                  Contact Me
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section id="about" className="bg-muted py-12 md:py-20">
          <div className="container mx-auto px-4">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
              <div>
                <h2 className="mb-4 text-2xl font-bold text-foreground">About Me</h2>
                <p className="text-muted-foreground">
                  I am a full-stack developer with a passion for creating beautiful and functional web applications. I
                  have experience in a variety of technologies, including React, Node.js, and MongoDB.
                </p>
              </div>
              <div>
                <h2 className="mb-4 text-2xl font-bold text-foreground">Skills</h2>
                <div className="grid grid-cols-2 gap-4">
                  <div className="rounded-md bg-background p-4 shadow-sm">
                    <h3 className="mb-2 text-lg font-medium text-foreground">Front-End</h3>
                    <ul className="space-y-2 text-muted-foreground">
                      <li>React</li>
                      <li>HTML/CSS</li>
                      <li>JavaScript</li>
                      <li>TypeScript</li>
                    </ul>
                  </div>
                  <div className="rounded-md bg-background p-4 shadow-sm">
                    <h3 className="mb-2 text-lg font-medium text-foreground">Back-End</h3>
                    <ul className="space-y-2 text-muted-foreground">
                      <li>Node.js</li>
                      <li>Express</li>
                      <li>MongoDB</li>
                      <li>SQL</li>
                    </ul>
                  </div>
                  <div className="rounded-md bg-background p-4 shadow-sm">
                    <h3 className="mb-2 text-lg font-medium text-foreground">Tools</h3>
                    <ul className="space-y-2 text-muted-foreground">
                      <li>Git</li>
                      <li>GitHub</li>
                      <li>Figma</li>
                      <li>VS Code</li>
                    </ul>
                  </div>
                  <div className="rounded-md bg-background p-4 shadow-sm">
                    <h3 className="mb-2 text-lg font-medium text-foreground">Other</h3>
                    <ul className="space-y-2 text-muted-foreground">
                      <li>Agile Methodologies</li>
                      <li>Responsive Design</li>
                      <li>SEO</li>
                      <li>Accessibility</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="projects" className="bg-background py-12 md:py-20">
          <div className="container mx-auto px-4">
            <h2 className="mb-8 text-2xl font-bold text-foreground">My Projects</h2>
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="rounded-md bg-muted p-4 shadow-sm">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Project 1"
                  className="mb-4 h-48 w-full rounded-md object-cover"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <h3 className="mb-2 text-lg font-medium text-foreground">Project 1</h3>
                <p className="text-muted-foreground">A web application built with React, Node.js, and MongoDB.</p>
                <div className="mt-4 flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    View Project
                  </Link>
                </div>
              </div>
              <div className="rounded-md bg-muted p-4 shadow-sm">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Project 2"
                  className="mb-4 h-48 w-full rounded-md object-cover"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <h3 className="mb-2 text-lg font-medium text-foreground">Project 2</h3>
                <p className="text-muted-foreground">A responsive e-commerce website built with React and Shopify.</p>
                <div className="mt-4 flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    View Project
                  </Link>
                </div>
              </div>
              <div className="rounded-md bg-muted p-4 shadow-sm">
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={300}
                  alt="Project 3"
                  className="mb-4 h-48 w-full rounded-md object-cover"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <h3 className="mb-2 text-lg font-medium text-foreground">Project 3</h3>
                <p className="text-muted-foreground">
                  A mobile-first web application built with React Native and Firebase.
                </p>
                <div className="mt-4 flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    View Project
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="bg-muted py-12 md:py-20">
          <div className="container mx-auto px-4">
            <h2 className="mb-8 text-2xl font-bold text-foreground">Contact Me</h2>
            <form className="mx-auto max-w-md space-y-4">
              <div>
                <label htmlFor="name" className="mb-2 block text-sm font-medium text-foreground">
                  Name
                </label>
                <Input
                  id="name"
                  type="text"
                  placeholder="John Doe"
                  className="w-full rounded-md border border-input bg-background p-2 text-foreground shadow-sm transition-colors focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                />
              </div>
              <div>
                <label htmlFor="email" className="mb-2 block text-sm font-medium text-foreground">
                  Email
                </label>
                <Input
                  id="email"
                  type="email"
                  placeholder="john@example.com"
                  className="w-full rounded-md border border-input bg-background p-2 text-foreground shadow-sm transition-colors focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                />
              </div>
              <div>
                <label htmlFor="message" className="mb-2 block text-sm font-medium text-foreground">
                  Message
                </label>
                <Textarea
                  id="message"
                  placeholder="Your message..."
                  className="w-full rounded-md border border-input bg-background p-2 text-foreground shadow-sm transition-colors focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary"
                />
              </div>
              <div className="flex justify-end">
                <Button
                  type="submit"
                  className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                >
                  Send Message
                </Button>
              </div>
            </form>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-4">
        <div className="container mx-auto flex items-center justify-between px-4">
          <p className="text-sm text-muted-foreground">&copy; 2024 John Doe. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-sm font-medium text-foreground hover:underline" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="text-sm font-medium text-foreground hover:underline" prefetch={false}>
              Terms of Service
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
